version: "3"

services:

  mongo:
    image: mongo:latest
    volumes:
      - codart_3_data:/data/db
      - codart_3_dataConfig:/data/configdb
      
  node1:
    image: akshitgrover/codart_3:v1
    volumes:
      - codart_3_uploads:/app/uploads
    ports:
      - "3000:3000"
  
  node2:
    image: akshitgrover/codart_3:v1
    environment:
      - PORT=3001
    volumes:
      - codart_3_uploads:/app/uploads
    ports:
      - "3001:3001"

volumes:
  codart_3_uploads:
  codart_3_data:
  codart_3_dataConfig:
